---
- hosts: test-server

  tasks:
  # Start a website

  - name: Create directory
    win_file:
      path: C:\sites\test-web
      state: directory

  - name: Acme IIS site
    win_iis_website:
      name: Acme
      state: started
      port: 80
      ip: "{{iis_ip}}"
      hostname: "{{hostname}}"
      application_pool: test-web
      physical_path: C:\sites\test-web
      parameters: logfile.directory:C:\sites\logs
    register: website

  # Remove Default Web Site and the standard port 80 binding
  - name: Remove Default Web Site
    win_iis_website:
      name: "Default Web Site"
      state: absent