---
- hosts: test-server

  tasks:
    - name: Change the hostname to sample-hostname
      win_hostname:
        name: "{{ hostname }}"
      register: res

    - name: Reboot
      win_reboot:
      when: res.reboot_required