---
#This playbook changes the default shell on windows 
# https://docs.ansible.com/ansible/latest/os_guide/windows_ssh.html

- hosts: test

  tasks:
   - name: set the default shell to PowerShell
     ansible.windows.win_regedit:
       path: HKLM:\SOFTWARE\OpenSSH
       name: DefaultShell
       data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
       type: string
       state: present

   - name: reset SSH connection after shell change
     ansible.builtin.meta: reset_connection

   - name: set the default shell to cmd
     ansible.windows.win_regedit:
       path: HKLM:\SOFTWARE\OpenSSH
       name: DefaultShell
       state: absent

   - name: reset SSH connection after shell change
     ansible.builtin.meta: reset_connection